export const USER_CREATED = 'USER_CREATED';


export const USER_CREATED_SESSION_REGISTERED =
  'USER_CREATED_SESSION_REGISTERED';

export const USER_LOGIN = 'USER_LOGIN';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_DELETED = 'USER_DELETED';

export const USER_PERMISSION_CHANGE = 'USER_PERMISSION_CHANGE';
